### ISSUE TITLE
use can edit date of spending

### ISSUE THREAD

**Issue by alexalannunes** [daviaquino87/MyPet-API#37]

**Comment by daviaquino87** [comment]
This function already created.
check the part -> [click here](https://github.com/daviaquino87/MyPet-API#atualizar-uma-compra)

**Comment by alexalannunes** [comment]
![image](https://github.com/daviaquino87/MyPet-API/assets/16847836/c06fe686-0c7c-4afc-a55a-c1e2e8494406)

![image](https://github.com/daviaquino87/MyPet-API/assets/16847836/7b746839-447d-4563-b8e4-ce352498e2a1)

**Comment by daviaquino87** [comment]
![image](https://github.com/daviaquino87/MyPet-API/assets/53793223/0a7fda53-e3c4-4fea-8078-c23c9c27c57b)

Date edit issue fixed
